// Mock data for development
export const mockPlayers = [
  {
    id: '1',
    name: 'Virat Kohli',
    team: 'Team A',
    role: 'batsman',
    city: 'Delhi',
    battingStyle: 'RHB',
    bowlingStyle: null,
    isWicketKeeper: false,
    matchesPlayed: 45,
    runs: 2345,
    wickets: 0,
    strikeRate: 145.5,
    economy: 0,
    status: 'active',
    phone: '+91 9876543210',
    email: 'virat@example.com',
  },
  {
    id: '2',
    name: 'Jasprit Bumrah',
    team: 'Team B',
    role: 'bowler',
    city: 'Mumbai',
    battingStyle: 'RHB',
    bowlingStyle: 'RHB',
    isWicketKeeper: false,
    matchesPlayed: 42,
    runs: 120,
    wickets: 89,
    strikeRate: 85.2,
    economy: 6.8,
    status: 'active',
    phone: '+91 9876543211',
    email: 'bumrah@example.com',
  },
  {
    id: '3',
    name: 'Rohit Sharma',
    team: 'Team A',
    role: 'batsman',
    city: 'Mumbai',
    battingStyle: 'RHB',
    bowlingStyle: null,
    isWicketKeeper: false,
    matchesPlayed: 48,
    runs: 2890,
    wickets: 2,
    strikeRate: 152.3,
    economy: 7.2,
    status: 'active',
    phone: '+91 9876543212',
    email: 'rohit@example.com',
  },
  {
    id: '4',
    name: 'Ravindra Jadeja',
    team: 'Team C',
    role: 'allrounder',
    city: 'Chennai',
    battingStyle: 'LHB',
    bowlingStyle: 'LHB',
    isWicketKeeper: false,
    matchesPlayed: 50,
    runs: 1567,
    wickets: 67,
    strikeRate: 138.9,
    economy: 7.1,
    status: 'active',
    phone: '+91 9876543213',
    email: 'jadeja@example.com',
  },
  {
    id: '5',
    name: 'MS Dhoni',
    team: 'Team B',
    role: 'wicketkeeper',
    city: 'Ranchi',
    battingStyle: 'RHB',
    bowlingStyle: null,
    isWicketKeeper: true,
    matchesPlayed: 52,
    runs: 2100,
    wickets: 0,
    strikeRate: 142.5,
    economy: 0,
    status: 'active',
    phone: '+91 9876543214',
    email: 'dhoni@example.com',
  },
  {
    id: '6',
    name: 'KL Rahul',
    team: 'Team A',
    role: 'batsman',
    city: 'Bangalore',
    battingStyle: 'RHB',
    bowlingStyle: null,
    isWicketKeeper: false,
    matchesPlayed: 40,
    runs: 1890,
    wickets: 0,
    strikeRate: 140.2,
    economy: 0,
    status: 'active',
    phone: '+91 9876543215',
    email: 'rahul@example.com',
  },
  {
    id: '7',
    name: 'Mohammed Shami',
    team: 'Team B',
    role: 'bowler',
    city: 'Delhi',
    battingStyle: 'RHB',
    bowlingStyle: 'RHB',
    isWicketKeeper: false,
    matchesPlayed: 38,
    runs: 95,
    wickets: 76,
    strikeRate: 78.5,
    economy: 7.0,
    status: 'active',
    phone: '+91 9876543216',
    email: 'shami@example.com',
  },
  {
    id: '8',
    name: 'Yuzvendra Chahal',
    team: 'Team C',
    role: 'bowler',
    city: 'Bangalore',
    battingStyle: 'RHB',
    bowlingStyle: 'RHB',
    isWicketKeeper: false,
    matchesPlayed: 35,
    runs: 45,
    wickets: 64,
    strikeRate: 65.0,
    economy: 7.5,
    status: 'active',
    phone: '+91 9876543217',
    email: 'chahal@example.com',
  },
  {
    id: '9',
    name: 'Rishabh Pant',
    team: 'Team A',
    role: 'wicketkeeper',
    city: 'Delhi',
    battingStyle: 'LHB',
    bowlingStyle: null,
    isWicketKeeper: true,
    matchesPlayed: 43,
    runs: 1780,
    wickets: 0,
    strikeRate: 148.3,
    economy: 0,
    status: 'active',
    phone: '+91 9876543218',
    email: 'pant@example.com',
  },
  {
    id: '10',
    name: 'Hardik Pandya',
    team: 'Team B',
    role: 'allrounder',
    city: 'Mumbai',
    battingStyle: 'RHB',
    bowlingStyle: 'RHB',
    isWicketKeeper: false,
    matchesPlayed: 46,
    runs: 1650,
    wickets: 42,
    strikeRate: 155.8,
    economy: 8.2,
    status: 'active',
    phone: '+91 9876543219',
    email: 'pandya@example.com',
  },
]

export const mockTeams = [
  {
    id: '1',
    name: 'Team A',
    captain: 'Virat Kohli',
    city: 'Delhi',
    country: 'India',
    matchesPlayed: 25,
    wins: 18,
    losses: 7,
    totalRuns: 12500,
    totalWickets: 150,
  },
  {
    id: '2',
    name: 'Team B',
    captain: 'MS Dhoni',
    city: 'Chennai',
    country: 'India',
    matchesPlayed: 24,
    wins: 16,
    losses: 8,
    totalRuns: 11800,
    totalWickets: 145,
  },
  {
    id: '3',
    name: 'Team C',
    captain: 'Rohit Sharma',
    city: 'Mumbai',
    country: 'India',
    matchesPlayed: 23,
    wins: 15,
    losses: 8,
    totalRuns: 11200,
    totalWickets: 138,
  },
  {
    id: '4',
    name: 'Team D',
    captain: 'Kane Williamson',
    city: 'Auckland',
    country: 'New Zealand',
    matchesPlayed: 22,
    wins: 14,
    losses: 8,
    totalRuns: 10800,
    totalWickets: 132,
  },
  {
    id: '5',
    name: 'Team E',
    captain: 'Steve Smith',
    city: 'Sydney',
    country: 'Australia',
    matchesPlayed: 26,
    wins: 19,
    losses: 7,
    totalRuns: 13000,
    totalWickets: 155,
  },
  {
    id: '6',
    name: 'Team F',
    captain: 'Joe Root',
    city: 'London',
    country: 'England',
    matchesPlayed: 24,
    wins: 17,
    losses: 7,
    totalRuns: 12000,
    totalWickets: 148,
  },
]

export const mockMatches = [
  {
    id: '1',
    tournament: 'IPL 2024',
    teamA: 'Team A',
    teamB: 'Team B',
    date: '2024-01-15',
    time: '19:00',
    location: 'Mumbai',
    status: 'completed',
    result: 'Team A won by 45 runs',
    teamAScore: '185/6',
    teamBScore: '140/8',
  },
  {
    id: '2',
    tournament: 'IPL 2024',
    teamA: 'Team C',
    teamB: 'Team A',
    date: '2024-01-18',
    time: '19:00',
    location: 'Delhi',
    status: 'live',
    result: 'In Progress',
    teamAScore: '120/3',
    teamBScore: '0/0',
  },
  {
    id: '3',
    tournament: 'IPL 2024',
    teamA: 'Team B',
    teamB: 'Team C',
    date: '2024-01-20',
    time: '15:30',
    location: 'Bangalore',
    status: 'scheduled',
    result: '-',
    teamAScore: '-',
    teamBScore: '-',
  },
]

export const mockTournaments = [
  {
    id: '1',
    name: 'IPL 2024',
    startDate: '2024-01-01',
    endDate: '2024-03-31',
    totalMatches: 60,
    totalTeams: 8,
    status: 'ongoing',
  },
  {
    id: '2',
    name: 'World Cup 2024',
    startDate: '2024-06-01',
    endDate: '2024-07-15',
    totalMatches: 45,
    totalTeams: 12,
    status: 'upcoming',
  },
]

export const mockNotifications = [
  {
    id: '1',
    title: 'Match Update',
    message: 'Team A vs Team B match is starting now!',
    imageUrl: '',
    sentAt: '2024-01-15T19:00:00Z',
    status: 'sent',
    totalReceivers: 1000,
  },
  {
    id: '2',
    title: 'Tournament Announcement',
    message: 'IPL 2024 registration is now open',
    imageUrl: '',
    sentAt: '2024-01-10T10:00:00Z',
    status: 'sent',
    totalReceivers: 5000,
  },
]

export const mockDashboardStats = {
  totalMatches: 125,
  totalTournaments: 8,
  totalTeams: 12,
  totalPlayers: 156,
  totalRuns: 125000,
  totalWickets: 2500,
}

// Generate mock users with signup dates
export const mockUsers = Array.from({ length: 30 }, (_, index) => {
  const names = [
    'Aarav Patel', 'Priya Sharma', 'Rahul Kumar', 'Sneha Reddy', 'Vikram Singh',
    'Ananya Desai', 'Karan Mehta', 'Divya Joshi', 'Arjun Shah', 'Meera Nair',
    'Rohan Agarwal', 'Kavya Iyer', 'Aditya Menon', 'Shreya Rao', 'Nikhil Pillai',
    'Isha Gupta', 'Ravi Malhotra', 'Pooja Verma', 'Siddharth Jain', 'Neha Kapoor',
    'Aman Tiwari', 'Riya Chaturvedi', 'Varun Dubey', 'Tanvi Saxena', 'Kunal Mishra',
    'Anjali Trivedi', 'Rohit Pandey', 'Swati Bhatt', 'Akash Goyal', 'Pallavi Agarwal',
  ]
  const emails = names.map(name => 
    `${name.toLowerCase().replace(/\s+/g, '.')}@example.com`
  )
  const cities = ['Mumbai', 'Delhi', 'Bangalore', 'Chennai', 'Kolkata', 'Hyderabad', 'Pune', 'Ahmedabad']
  
  // Generate signup dates - latest 30 days
  const daysAgo = index
  const signupDate = new Date()
  signupDate.setDate(signupDate.getDate() - daysAgo)
  signupDate.setHours(Math.floor(Math.random() * 24))
  signupDate.setMinutes(Math.floor(Math.random() * 60))
  
  return {
    id: `user-${index + 1}`,
    name: names[index],
    email: emails[index],
    city: cities[index % cities.length],
    signupDate: signupDate.toISOString(),
    status: Math.random() > 0.2 ? 'active' : 'inactive',
    profileImage: `https://ui-avatars.com/api/?name=${encodeURIComponent(names[index])}&background=0E795D&color=fff&size=128`,
  }
}).sort((a, b) => new Date(b.signupDate).getTime() - new Date(a.signupDate).getTime())

